wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1654271529
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      4: 3.10.4
      5: 0.12.12
      8:
      - 3
      - 5
architecture:
  desc: null
  value: Resnet18
batch_size:
  desc: null
  value: 1024
dataset:
  desc: null
  value: FashionMNIST
learning_rate:
  desc: null
  value: 0.0001
loss_type:
  desc: null
  value: poly
max_epochs:
  desc: null
  value: 1000
n:
  desc: null
  value: 1024
pretrained:
  desc: null
  value: false
