wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1654642189
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      4: 3.10.4
      5: 0.12.12
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 100
epochs:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.01
momentum:
  desc: null
  value: 0.9
n:
  desc: null
  value: 2048
