wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1654082706
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 24
      4: 3.10.4
      5: 0.12.12
      8:
      - 3
      - 5
architecture:
  desc: null
  value: Resnet18-binary
batch_size:
  desc: null
  value: 32
dataset:
  desc: null
  value: FashionMNIST-binary
learning_rate:
  desc: null
  value: 0.01
loss_type:
  desc: null
  value: ce
max_epochs:
  desc: null
  value: 1000
n:
  desc: null
  value: 32
pretrained:
  desc: null
  value: true
