wandb_version: 1

SNR:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    cli_version: 0.12.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1649681589
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      4: 3.10.4
      5: 0.12.12
      8:
      - 3
      - 5
class_sep:
  desc: null
  value: 3.1622776601683795
label_noise_prob:
  desc: null
  value: 0
n_clusters_per_class:
  desc: null
  value: 1
n_features:
  desc: null
  value: 5000
n_informative:
  desc: null
  value: 5000
n_redundant:
  desc: null
  value: 0
n_repeated:
  desc: null
  value: 0
n_test:
  desc: null
  value: 10000.0
n_train:
  desc: null
  value: 200
n_useless:
  desc: null
  value: 0
s:
  desc: null
  value: 1
tau:
  desc: null
  value: 1.0
