wandb_version: 1

SNR:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1653132891
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      4: 3.10.4
      5: 0.12.16
      8:
      - 3
      - 5
class_sep:
  desc: null
  value: 2.23606797749979
label_noise_prob:
  desc: null
  value: 0
n_clusters_per_class:
  desc: null
  value: 1
n_features:
  desc: null
  value: 100
n_informative:
  desc: null
  value: 100
n_redundant:
  desc: null
  value: 0
n_repeated:
  desc: null
  value: 0
n_test:
  desc: null
  value: 10000.0
n_train:
  desc: null
  value: 1000
n_useless:
  desc: null
  value: 0
s:
  desc: null
  value: 1
tau:
  desc: null
  value: 1.0
