wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1654689083
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 16
      4: 3.10.4
      5: 0.12.12
      8:
      - 3
      - 5
architecture:
  desc: null
  value: Convnet
batch_size:
  desc: null
  value: 64
dataset:
  desc: null
  value: FashionMNIST-binary
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.001
loss_type:
  desc: null
  value: ce
n:
  desc: null
  value: 64
